In [1]:
import numpy as np

In [2]:
array1 = np.array([[10, 8], [3, 5]])
array1_turn=np.linalg.inv(array1)
array1_turn

array([[ 0.19230769, -0.30769231],
       [-0.11538462,  0.38461538]])

In [3]:
array1@array1_turn

array([[ 1.00000000e+00,  0.00000000e+00],
       [-1.38777878e-17,  1.00000000e+00]])

In [5]:
a, b=np.linalg.eig(array1)
print("eigenvalue:",a)
print("eigenvector:",b)

eigenvalue: [13.  2.]
eigenvector: [[ 0.93632918 -0.70710678]
 [ 0.35112344  0.70710678]]


In [7]:
s,v,d=np.linalg.svd(array1)
s

array([[-0.91663818, -0.39971796],
       [-0.39971796,  0.91663818]])

In [8]:
v

array([13.94721714,  1.86417116])

In [9]:
d

array([[-0.74319741, -0.6690722 ],
       [-0.6690722 ,  0.74319741]])